Task_1_1_2
babadzakich/OOP pull request #2
Opened 2024-09-13 06:22 UTC by babadzakich

2024-09-17 07:52 UTC, Vovadinamik8913 commented
Wish you were here - лучший альбом Pink FLoyd

2024-09-18 11:51 UTC, shadrina requested changes

2024-09-18 11:51 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Card.java
> +    ArrayList<Integer> aces;
См. инкапсуляция, модификаторы доступа.
См. изменяемость структуры данных, модификатор final.

2024-09-18 11:51 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Card.java
> +    ArrayList<Integer> aces;
Вот эти два поля не очень понятны. Зачем они тут?

2024-09-18 11:51 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Deck.java
> +    public static void draw_cards(ArrayList<Card> player) {
1 В Java мы используем только camelCase

2024-09-18 11:51 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Deck.java
> +    public static void draw_cards(ArrayList<Card> player) {
2 В публичных сигнатурах мы стараемся не завязываться на конкретных реализациях используемых типов. Чем более общие типы в сигнатуре, тем для больших юзкейсов можно вызвать метод.

`ArrayList<T>` - это конкретная реализация для контейнера `List<T>`. ная реализация для контейнера `List<T>`.

2024-09-18 11:51 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Deck.java
> +        player.add(deck.get(deck_card_index++));
camelCase в любых именах

2024-09-18 11:51 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Deck.java
> +
Если ты хочешь синглтон, сделай синглон по [паттерну](https://en.wikipedia.org/wiki/Singleton_pattern). Класс с полностью статическим состоянием имеет смысл только тогда, когда он как утилита, а все его поля - не только статические, но и финальные.

В данном случае у тебя обычное изменяемое состояние, я не вижу причин все делать static.

2024-09-18 11:51 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Game.java
> +
Аналогично класс с полностью статическим состоянием. Почему?

2024-09-18 11:51 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Game.java
> +
Надо понимать, что статические поля - это состояние всего класса, а не конкретного объекта. Т.е. это общее состояние для всех объектов этого класса, где каждый из этих объектов может это состояние мутировать (ту его часть, которая не final). 

Потенциально это опасно, так как один отдельный объект имеет влияние на состояние всех остальных.

2024-09-18 11:51 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Game.java
> +
Почему player и dealer имеют видимость package-private? Защищать стоит всё.

2024-09-18 15:40 UTC, babadzakich commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Card.java
> +    ArrayList<Integer> aces;
ну у меня была идея-фикс хранить сумму всех карт в колоде в самом первом элементе колоды и вызывать когда надо, но я просто не понял как это сделать правильно

2024-09-23 12:03 UTC, shadrina requested changes
Все смешалось - и первая лаба, и вторая, и `.idea` в корне.

2024-09-23 12:03 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Kards.java
> +enum Kards {
enum'ам тоже можно навешивать модификаторы доступа. Если, конечно, в этом есть необходимость.

2024-09-23 12:03 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Mast.java
> +    public String toString() {
`@Override`

2024-09-23 12:03 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/PlayerDeck.java
> +            aces.add(deck.size() - 1);
Я вижу 5 раз выражение `deck.size() - 1`. Может, `final var lastCardIndex = deck.size() - 1`?

2024-09-23 12:03 UTC, shadrina commented on Task_1_1_2/src/test/java/ru/nsu/chuvashov/bj/GameTest.java
> +            System.setIn(in2);
Что происходит?...

2024-09-23 12:03 UTC, shadrina commented on Task_1_1_2/src/test/java/ru/nsu/chuvashov/bj/GameTest.java
> +        assertTrue(true);
Не так я себе представляю unit-тесты.

2024-09-23 16:07 UTC, babadzakich commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/PlayerDeck.java
> +            aces.add(deck.size() - 1);
А у меня там в руку игрока добавляются карты, в итоге размер деки будет изменяться, а в переменной он не изменится

2024-09-24 12:11 UTC, shadrina requested changes
Критичнее всего, что в PR на вторую лабу присутствуют изменения первой.

Не надо удалять первую задачу из main, она должна там остаться.

2024-09-24 12:11 UTC, shadrina commented on Task_1_1_2/src/test/java/ru/nsu/chuvashov/bj/GameTest.java
> +            System.setIn(in2);
Вопрос остается открытым.

2024-09-24 12:11 UTC, shadrina commented on Task_1_1_2/src/test/java/ru/nsu/chuvashov/bj/GameTest.java
> +        assertTrue(true);
Но юнит-тестов не появилось?

2024-10-01 07:53 UTC, shadrina requested changes

2024-10-01 07:53 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Card.java
> +    int value;
Нет модификаторов доступа

2024-10-01 07:53 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Kards.java
> +
То же самое

2024-10-01 07:53 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/chuvashov/bj/Kards.java
> +    Kards(String name, int value) {
Для всех членов класса можно указывать область видимости

2024-10-01 07:53 UTC, shadrina commented on Task_1_1_2/src/test/java/ru/nsu/chuvashov/bj/GameTest.java
> +            throw e;
Это рантайм исключение, которое выкидывает JVM. До него лучше не доводить

2024-10-01 08:53 UTC, shadrina approved these changes

2024-10-01 08:56 UTC, merged